services:
  node1:
    build: .
    networks: [kvnet]
    ports:
      - "50051:50051"
      - "6060:6060"
    command:
      - --mode=${MODE:-eventual}
      - --port=50051
      - --peers=node2:50052,node3:50053
      - --peer-delay=${PEER_DELAY:-0}
      - --pprof=0.0.0.0:6060

  node2:
    build: .
    networks: [kvnet]
    ports:
      - "50052:50052"
    command:
      - --mode=${MODE:-eventual}
      - --port=50052
      - --peers=node1:50051,node3:50053
      - --peer-delay=${PEER_DELAY:-0}

  node3:
    build: .
    networks: [kvnet]
    ports:
      - "50053:50053"
    command:
      - --mode=${MODE:-eventual}
      - --port=50053
      - --peers=node1:50051,node2:50052
      - --peer-delay=${PEER_DELAY:-0}

networks:
  kvnet:
    driver: bridge
